---
- hosts: spacewalk-server
  become: yes
  pre_tasks:
    - hostname: name=spacewalk02
  roles:
    - spacewalk
    - role: iptables
      firewall_allowed_tcp_ports:
      - 22
      - 80
      - 443
      - 5222
      - 5269


- hosts: spacewalk-server
  become: yes

  vars_prompt:
    - name: "ready_to_go"
      prompt: "Login to the Spacewalk and set up and admin account. Hit Enter when ready"
      private: No

    - name: "admin_password"
      prompt: "Admin Password"
      default: "test123"
      private: yes

  roles:
    - role: spacewalk-customisations
      spacewalk_admin_password: "{{admin_password}}"
    - role: spacewalk-client
